import type { PGliteInterface } from '@electric-sql/pglite'
import { flushStatistics } from './autovacuum'
import {
  CATEGORIES,
  COUNTRIES,
  DESCRIPTION_SENTENCES,
  FIRST_NAMES,
  LAST_NAMES,
  PRODUCT_ADJECTIVES,
  PRODUCT_NOUNS,
  STREETS,
} from './seedWords'

/**
 * Bump this whenever the generated data changes (this file or seedWords.ts).
 * Visitors with an older seed are offered a reset. See docs/DATA.md.
 */
export const SEED_VERSION = 1

/** The tables the seed creates, in foreign-key order. */
export const SEED_TABLES = ['categories', 'products', 'customers', 'orders', 'order_items']

/** Creates pageinspect and pg_buffercache. Safe to run more than once. */
export async function installExtensions(db: PGliteInterface) {
  await db.exec(`
    CREATE EXTENSION IF NOT EXISTS pageinspect;
    CREATE EXTENSION IF NOT EXISTS pg_buffercache;
  `)
}

export interface SeedInfo {
  /** The SEED_VERSION the data was generated with. */
  version: number
  seededAt: Date
}

/**
 * When and with which seed version this database was generated; null if it was never seeded.
 * Stored in its own schema so it stays out of the learner's way.
 */
export async function readSeedInfo(db: PGliteInterface): Promise<SeedInfo | null> {
  const exists = await db.query<{ found: boolean }>(
    `SELECT to_regclass('visualizer.seed_info') IS NOT NULL AS found`,
  )
  if (!exists.rows[0].found) return null
  const result = await db.query<{ version: number; seeded_at: Date }>(
    'SELECT version, seeded_at FROM visualizer.seed_info',
  )
  const row = result.rows[0]
  return row ? { version: row.version, seededAt: row.seeded_at } : null
}

/** Seeds a database that has never been seeded. Leaves an existing database alone. */
export async function ensureSeeded(db: PGliteInterface) {
  if ((await readSeedInfo(db)) === null) await seedDatabase(db)
}

/** Generates the online-store tables, then VACUUM ANALYZEs them. Expects an empty database. */
export async function seedDatabase(db: PGliteInterface) {
  // One transaction: a seed interrupted by closing the tab leaves nothing behind.
  await db.exec(`BEGIN; ${SEED_SQL} COMMIT;`)
  // Publish the seed's insert counts first. Otherwise they reach
  // pg_stat_user_tables after VACUUM ANALYZE has reset them, and every table
  // looks twice its size with all its rows changed since the last analyze.
  await flushStatistics(db)
  // VACUUM can't run inside a transaction. It sets hint bits and the visibility map,
  // and ANALYZE gives the planner statistics, as autovacuum would on a real server.
  await db.exec(`VACUUM ANALYZE ${SEED_TABLES.join(', ')}`)
}

/**
 * Drops everything the learner created (every non-system schema, including public),
 * then seeds again from scratch.
 */
export async function resetDatabase(db: PGliteInterface) {
  await db.exec(`
    DO $$
    DECLARE
      schema_name text;
    BEGIN
      FOR schema_name IN
        SELECT nspname FROM pg_namespace
        WHERE nspname NOT LIKE 'pg\\_%' AND nspname <> 'information_schema'
      LOOP
        EXECUTE format('DROP SCHEMA %I CASCADE', schema_name);
      END LOOP;
    END $$;
    CREATE SCHEMA public;
  `)
  // The extensions lived in the public schema, so they were dropped with it.
  await installExtensions(db)
  await seedDatabase(db)
}

/** Writes a JavaScript list as a SQL text array literal. */
function textArray(values: string[]) {
  return `ARRAY[${values.map((value) => `'${value.replaceAll("'", "''")}'`).join(', ')}]`
}

const countryRows = COUNTRIES.map(
  ([country, weight, cities], index) => `(${index + 1}, '${country}', ${weight}, ${textArray(cities)})`,
).join(',\n    ')

const categoryRows = CATEGORIES.map(
  ([name, description], index) => `(${index + 1}, '${name}', '${description}')`,
).join(',\n    ')

// Notes on determinism: setseed() fixes the sequence of random() values, and every
// INSERT lists rows in a fixed order (ORDER BY), so every visitor gets byte-identical
// pages. random(min, max) returns an integer in [min, max] (Postgres 17+).
// Indexes and constraints are added after loading, so each B-tree is built in one pass
// and comes out compact, like an index created on an existing table.
const SEED_SQL = `
SELECT setseed(0.4242);

-- Seed bookkeeping, kept out of the public schema.
CREATE SCHEMA visualizer;
CREATE TABLE visualizer.seed_info (version integer NOT NULL, seeded_at timestamptz NOT NULL);

-- Picks a random element of an array. Temporary: gone when the session ends.
CREATE FUNCTION pg_temp.pick(choices text[]) RETURNS text
  LANGUAGE sql VOLATILE
  AS $$ SELECT choices[random(1, cardinality(choices))] $$;

CREATE TABLE categories (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  description text NOT NULL
);

CREATE TABLE products (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  category_id integer NOT NULL,
  name text NOT NULL,
  price numeric(10, 2) NOT NULL,
  description text NOT NULL,
  created_at timestamp NOT NULL
);

CREATE TABLE customers (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  email text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  country text NOT NULL,
  city text NOT NULL,
  signup_date date NOT NULL
);

CREATE TABLE orders (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  customer_id integer NOT NULL,
  order_date date NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'shipped', 'delivered', 'cancelled')),
  total numeric(10, 2) NOT NULL,
  shipping_address text NOT NULL
);

CREATE TABLE order_items (
  order_id integer NOT NULL,
  line_no integer NOT NULL,
  product_id integer NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric(10, 2) NOT NULL
);

-- categories: 12 rows, one page.
INSERT INTO categories (id, name, description)
VALUES
    ${categoryRows};

-- products: 1,000 wide rows (descriptions are a few hundred bytes).
INSERT INTO products (id, category_id, name, price, description, created_at)
SELECT
  g,
  random(1, ${CATEGORIES.length}),
  pg_temp.pick(${textArray(PRODUCT_ADJECTIVES)}) || ' ' || pg_temp.pick(${textArray(PRODUCT_NOUNS)}),
  -- Squaring skews prices toward the cheap end: $2 to $500.
  round((2 + 498 * random() ^ 2)::numeric, 2),
  pg_temp.pick(${textArray(DESCRIPTION_SENTENCES)}) || ' ' || pg_temp.pick(${textArray(DESCRIPTION_SENTENCES)})
    || ' ' || pg_temp.pick(${textArray(DESCRIPTION_SENTENCES)}) || ' ' || pg_temp.pick(${textArray(DESCRIPTION_SENTENCES)}),
  timestamp '2022-01-01' + random() * interval '1095 days'
FROM generate_series(1, 1000) AS g
ORDER BY g;

-- customers: 10,000 rows. Countries are weighted (about 40% United States);
-- names come from a few hundred first and last names, so names repeat.
CREATE TEMP TABLE country_weights AS
SELECT
  country,
  cities,
  (sum(weight) OVER (ORDER BY ord) - weight) / sum(weight) OVER () AS lower_bound,
  sum(weight) OVER (ORDER BY ord) / sum(weight) OVER () AS upper_bound
FROM (VALUES
    ${countryRows}
) AS c(ord, country, weight, cities);

INSERT INTO customers (id, email, first_name, last_name, country, city, signup_date)
SELECT
  r.g,
  lower(r.first_name || '.' || r.last_name) || r.g || '@example.com',
  r.first_name,
  r.last_name,
  w.country,
  pg_temp.pick(w.cities),
  -- Sign-ups spread evenly over 2019-2024, in id order.
  date '2019-01-01' + (r.g - 1) * 2191 / 10000
FROM (
  SELECT
    g,
    pg_temp.pick(${textArray(FIRST_NAMES)}) AS first_name,
    pg_temp.pick(${textArray(LAST_NAMES)}) AS last_name,
    random() AS country_draw
  FROM generate_series(1, 10000) AS g
) AS r
JOIN country_weights AS w ON r.country_draw >= w.lower_bound AND r.country_draw < w.upper_bound
ORDER BY r.g;

-- orders: 50,000 rows, staged first so each order's total can be computed from its items.
-- order_date rises with id, so the table is physically in date order. customer_id is random.
-- The newest orders are still pending or shipped; 2% of all orders are cancelled.
CREATE TEMP TABLE order_stage AS
SELECT
  g AS id,
  random(1, 10000) AS customer_id,
  date '2022-01-01' + (g - 1) * 1096 / 50000 AS order_date,
  CASE
    WHEN random() < 0.02 THEN 'cancelled'
    WHEN g > 48470 THEN 'pending'
    WHEN g > 45920 THEN 'shipped'
    ELSE 'delivered'
  END AS status,
  random(1, 7) AS item_count
FROM generate_series(1, 50000) AS g;

-- order_items: 1 to 7 lines per order (about 200,000 rows). Most lines have quantity 1.
CREATE TEMP TABLE item_stage AS
SELECT i.order_id, i.line_no, i.product_id, i.quantity, p.price AS unit_price
FROM (
  SELECT
    o.id AS order_id,
    line_no,
    random(1, 1000) AS product_id,
    CASE WHEN random() < 0.6 THEN 1 ELSE random(2, 5) END AS quantity
  FROM order_stage AS o
  CROSS JOIN LATERAL generate_series(1, o.item_count) AS line_no
  ORDER BY o.id, line_no
) AS i
JOIN products AS p ON p.id = i.product_id;

INSERT INTO orders (id, customer_id, order_date, status, total, shipping_address)
SELECT
  o.id,
  o.customer_id,
  o.order_date,
  o.status,
  t.total,
  random(1, 9999) || ' ' || pg_temp.pick(${textArray(STREETS)}) || ', ' || c.city || ', ' || c.country
FROM order_stage AS o
JOIN (
  SELECT order_id, sum(quantity * unit_price) AS total FROM item_stage GROUP BY order_id
) AS t ON t.order_id = o.id
JOIN customers AS c ON c.id = o.customer_id
ORDER BY o.id;

INSERT INTO order_items (order_id, line_no, product_id, quantity, unit_price)
SELECT order_id, line_no, product_id, quantity, unit_price
FROM item_stage
ORDER BY order_id, line_no;

DROP TABLE country_weights, order_stage, item_stage;
DROP FUNCTION pg_temp.pick(text[]);

-- The identity columns' sequences continue after the generated ids.
SELECT setval(pg_get_serial_sequence('categories', 'id'), max(id)) FROM categories;
SELECT setval(pg_get_serial_sequence('products', 'id'), max(id)) FROM products;
SELECT setval(pg_get_serial_sequence('customers', 'id'), max(id)) FROM customers;
SELECT setval(pg_get_serial_sequence('orders', 'id'), max(id)) FROM orders;

-- Starting indexes (docs/DATA.md). order_items.product_id, orders.status and
-- orders.order_date are deliberately left unindexed for learners to add.
ALTER TABLE categories ADD PRIMARY KEY (id);
ALTER TABLE products ADD PRIMARY KEY (id);
ALTER TABLE customers ADD PRIMARY KEY (id);
ALTER TABLE orders ADD PRIMARY KEY (id);
ALTER TABLE order_items ADD PRIMARY KEY (order_id, line_no);
ALTER TABLE customers ADD UNIQUE (email);
CREATE INDEX ON customers (last_name, first_name);
CREATE INDEX ON orders (customer_id, order_date);

-- Foreign keys. As in real Postgres, these don't create indexes.
ALTER TABLE products ADD FOREIGN KEY (category_id) REFERENCES categories;
ALTER TABLE orders ADD FOREIGN KEY (customer_id) REFERENCES customers;
ALTER TABLE order_items ADD FOREIGN KEY (order_id) REFERENCES orders;
ALTER TABLE order_items ADD FOREIGN KEY (product_id) REFERENCES products;

INSERT INTO visualizer.seed_info (version, seeded_at) VALUES (${SEED_VERSION}, now());
`
