import { expect, test } from '@playwright/test'
import { openApp, runSql, statusLines } from './editor'
import { treeItem } from './schemaTree'

// These two close gaps left by the first M1 PR (#3): they need the SQL editor to make the change.

test('tables, rows and indexes made in the editor are saved in the browser and outlast a reload', async ({ page }) => {
  await openApp(page)
  await runSql(
    page,
    `CREATE TABLE notes (id int PRIMARY KEY, body text);
     INSERT INTO notes VALUES (1, 'hello'), (2, 'world');
     CREATE INDEX orders_status_idx ON orders (status);`,
  )
  await expect(statusLines(page)).toHaveCount(3)
  await expect(treeItem(page, 'notes')).toBeVisible()

  await page.reload()
  await expect(treeItem(page, 'notes')).toBeVisible({ timeout: 60_000 })
  await runSql(page, `SELECT body FROM notes ORDER BY id;\nSELECT indexname FROM pg_indexes WHERE indexname = 'orders_status_idx';`)
  await expect(statusLines(page)).toHaveCount(2)
  await expect(page.getByTestId('result-table').locator('tbody td')).toHaveText(['orders_status_idx'])
  await runSql(page, 'SELECT body FROM notes ORDER BY id;')
  await expect(page.getByTestId('result-table').locator('tbody td')).toHaveText(['hello', 'world'])
})

test('an outdated sample-data version shows the reset banner; Reset database clears it', async ({ page }) => {
  await openApp(page)
  await expect(page.getByTestId('seed-outdated')).toHaveCount(0)

  // Pretend the data was generated by an older release.
  await runSql(page, 'UPDATE visualizer.seed_info SET version = 0;')
  await expect(page.getByTestId('seed-outdated')).toBeVisible()
  await page.reload()
  await expect(page.getByTestId('seed-outdated')).toBeVisible({ timeout: 60_000 })

  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Reset database' }).click()
  await expect(treeItem(page, 'orders')).toBeVisible({ timeout: 60_000 })
  await expect(page.getByTestId('seed-outdated')).toHaveCount(0)
})
